spring:
  datasource:
    url: jdbc:h2:mem:29cm
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: false
        show-sql: false
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: info

app:
  about: "dev"